version: "3"

services:
  mysql:
    image: "mariadb"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

  minio:
    image: 'bitnami/minio:2023.1.31'
    environment:
      MINIO_ROOT_USER: "AccessKey"
      MINIO_ROOT_PASSWORD: "SecretKey"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/var/lib/minio:delegated

volumes:
  mysql-data:
  minio-data:

