version: "3"

services:
  mysql:
    image: "mariadb"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

  minio:
    image: "minio/minio:RELEASE.2023-01-31T02-24-19Z"
    environment:
      MINIO_ROOT_USER: "AccessKey"
      MINIO_ROOT_PASSWORD: "SecretKey"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/var/lib/minio:delegated

volumes:
  mysql-data:
  minio-data:

