version: "3.2"

services:
  mysql:
    image: "mariadb:10.2.12"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:delegated
volumes:
  mysql-data:

