name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      minio:
        image: 'minio/minio'
        ports: ['9000:9000']
        env:
          MINIO_ACCESS_KEY: "AccessKey"
          MINIO_SECRET_KEY: "SecretKey"
      mysql:
        image: 'mariadb'
        ports: ['3306:3306']
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby: ['2.7', '3.0']

    env:
      S3_HOST: '127.0.0.1:9000'
      DB_HOST: '127.0.0.1:3306'

    steps:
      - uses: actions/checkout@v2
      - name: Wait service ports
        run: |
          npm install -g wait-port
          wait-port -t 15 localhost:9000
          wait-port -t 15 localhost:3306
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: { ruby-version: '${{ matrix.ruby }}' }
      - name: Setup project
        run: bin/setup
      - name: Run tests
        run: bin/rake ci
